// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthService service

func NewAuthServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthService service

type AuthService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	GetUserFromToken(ctx context.Context, in *GetUserFromTokenRequest, opts ...client.CallOption) (*GetUserFromTokenResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetUserFromToken(ctx context.Context, in *GetUserFromTokenRequest, opts ...client.CallOption) (*GetUserFromTokenResponse, error) {
	req := c.c.NewRequest(c.name, "AuthService.GetUserFromToken", in)
	out := new(GetUserFromTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
	GetUserFromToken(context.Context, *GetUserFromTokenRequest, *GetUserFromTokenResponse) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authService interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		GetUserFromToken(ctx context.Context, in *GetUserFromTokenRequest, out *GetUserFromTokenResponse) error
	}
	type AuthService struct {
		authService
	}
	h := &authServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.AuthServiceHandler.Login(ctx, in, out)
}

func (h *authServiceHandler) GetUserFromToken(ctx context.Context, in *GetUserFromTokenRequest, out *GetUserFromTokenResponse) error {
	return h.AuthServiceHandler.GetUserFromToken(ctx, in, out)
}
